<?php
/**
 * Language System - ResQTech
 * ระบบจัดการภาษา
 */

// ป้องกันการเข้าถึงโดยตรง
if (!defined('RESQTECH_APP')) {
    http_response_code(403);
    exit('Access Denied');
}

// ตั้งค่าภาษาเริ่มต้น
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = 'th';
}

// เปลี่ยนภาษาเมื่อมีการร้องขอ
if (isset($_GET['lang']) && in_array($_GET['lang'], ['th', 'en'])) {
    $_SESSION['language'] = $_GET['lang'];
}

$current_lang = $_SESSION['language'];

// ข้อความในภาษาต่างๆ
$translations = [
    'th' => [
        // หน้า Login
        'login_title' => 'เข้าสู่ระบบ',
        'login_subtitle' => 'ResQTech Notification System',
        'username' => 'ชื่อผู้ใช้',
        'password' => 'รหัสผ่าน',
        'username_placeholder' => 'กรอกชื่อผู้ใช้',
        'password_placeholder' => 'กรอกรหัสผ่าน',
        'login_button' => 'เข้าสู่ระบบ',
        'security_title' => 'ระบบความปลอดภัย',
        'security_session' => 'Session Timeout',
        'security_brute' => 'Brute Force Protection',
        'security_csrf' => 'CSRF Protection',
        'security_headers' => 'Secure Headers',
        'logout_success' => 'ออกจากระบบเรียบร้อยแล้ว',
        'session_timeout' => 'Session หมดอายุ กรุณาเข้าสู่ระบบใหม่',
        'login_failed' => 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
        'too_many_attempts' => 'คุณพยายาม Login ผิดหลายครั้ง กรุณารอ {minutes} นาที',
        'or_login_with' => 'หรือเข้าสู่ระบบด้วย',
        'sign_in_google' => 'เข้าสู่ระบบด้วย Google',
        
        // หน้า Index
        'system_title' => 'ResQTech System',
        'system_subtitle' => 'Smart Notification & Management Platform',
        'hello_user' => 'สวัสดี, {username}!',
        'login_time' => 'เข้าสู่ระบบเมื่อ: {time}',
        'logout' => 'ออกจากระบบ',
        'send_notification' => 'ส่งการแจ้งเตือน',
        'notification_title' => 'ส่งการแจ้งเตือน',
        'notification_desc' => 'กดปุ่มด้านล่างเพื่อส่งการแจ้งเตือนไปยัง LINE Official Account ทันที',
        'notification_message_label' => 'ข้อความ/รายละเอียด',
        'notification_message_placeholder' => 'พิมพ์รายละเอียดที่ต้องการส่งไปยัง LINE...',
        'send_button' => 'ส่งการแจ้งเตือน',
        'sending' => 'กำลังส่ง...',
        'send_success' => 'ส่งการแจ้งเตือนสำเร็จ!',
        'send_error' => 'เกิดข้อผิดพลาด! กรุณาตรวจสอบ Log',
        'connection_error' => 'ไม่สามารถเชื่อมต่อกับ Server ได้',
        'loading_clock' => 'กำลังโหลด...',
        
        // ทั่วไป
        'theme_toggle' => 'เปลี่ยนธีม',
        'language' => 'ภาษา',
        'thai' => 'ไทย',
        'english' => 'English',
        'profile' => 'โปรไฟล์',

        'nav_home' => 'หน้าหลัก',
        'nav_dashboard' => 'แดชบอร์ด',
        'nav_control' => 'ศูนย์ควบคุม',
        'nav_latency' => 'ความหน่วง',
        'nav_status' => 'สถานะ',
        'nav_history' => 'ประวัติ',
        'nav_diagnostics' => 'ตรวจสอบระบบ',
        'nav_live' => 'เรียลไทม์',
        'nav_logout' => 'ออกจากระบบ',
        'nav_more' => 'เพิ่มเติม',

        'common_refresh' => 'รีเฟรช',
        'common_raw_json' => 'ข้อมูลดิบ (JSON)',
        'common_last' => 'ล่าสุด',
        'common_count' => 'จำนวน',
        'common_live' => 'สด',
        'common_error' => 'ผิดพลาด',
        'common_loading' => 'กำลังโหลด...',
        'common_no_data' => 'ไม่มีข้อมูล',
        'common_fetch_failed' => 'ดึงข้อมูลไม่สำเร็จ',
        'common_auto_refresh' => 'รีเฟรชอัตโนมัติ',
        'common_off' => 'ปิด',
        'common_on' => 'เปิด',
        'common_limit' => 'ลิมิต',
        'common_action' => 'แอคชัน',
        'common_all' => 'ทั้งหมด',

        'page_dashboard_title' => 'แดชบอร์ด',
        'page_dashboard_subtitle' => 'ติดตามแบบเรียลไทม์',
        'dashboard_marquee_title' => 'ResQTech Dashboard',
        'dashboard_marquee_subtitle1' => 'ระบบติดตามเหตุฉุกเฉิน',
        'dashboard_marquee_subtitle2' => 'อัปเดตแบบเรียลไทม์',
        'dashboard_marquee_subtitle3' => 'ปกป้องตลอด 24/7',
        'dashboard_total_events' => 'เหตุการณ์ทั้งหมด',
        'dashboard_all_time' => 'ทั้งหมด',
        'dashboard_today_events' => 'เหตุการณ์วันนี้',
        'dashboard_last_24h' => '24 ชั่วโมงล่าสุด',
        'dashboard_recent' => 'ล่าสุด',
        'dashboard_esp32_status' => 'สถานะ ESP32',
        'dashboard_uptime' => 'อัปไทม์',
        'dashboard_last_heartbeat' => 'Heartbeat ล่าสุด',
        'dashboard_active_devices' => 'อุปกรณ์ที่ใช้งาน',
        'dashboard_active_devices_subtitle' => 'สถานะเรียลไทม์ของ ESP32 ทุกตัว',
        'dashboard_events_overview' => 'ภาพรวมเหตุการณ์',
        'dashboard_events_overview_subtitle' => 'สถิติเหตุการณ์ฉุกเฉิน',
        'dashboard_timeline_title' => 'ไทม์ไลน์กิจกรรม',
        'dashboard_timeline_subtitle' => 'กิจกรรม 7 วันล่าสุด',
        'dashboard_recent_events' => 'เหตุการณ์ล่าสุด',
        'dashboard_recent_events_subtitle' => 'การแจ้งเตือนฉุกเฉินล่าสุด',
        'dashboard_no_events_yet' => 'ยังไม่มีเหตุการณ์ที่บันทึกไว้',
        'dashboard_chart_today' => 'วันนี้',
        'dashboard_chart_last24h' => '24 ชม. ล่าสุด',
        'dashboard_chart_last7d' => '7 วันล่าสุด',
        'dashboard_chart_older' => 'ก่อนหน้านี้',
        'dashboard_chart_events' => 'เหตุการณ์',

        'control_room_title' => 'ศูนย์ควบคุม',
        'control_room_subtitle' => 'ResQTech War Room',
        'control_room_war_room' => 'WAR ROOM',
        'control_room_emergency_alert' => 'แจ้งเตือนฉุกเฉิน',
        'control_room_unknown_location' => 'ไม่ทราบสถานที่',
        'control_room_unknown_device' => 'ไม่ทราบอุปกรณ์',
        'control_room_acknowledge' => 'รับทราบ',
        'control_room_system_online' => 'ระบบออนไลน์',
        'control_room_system_offline' => 'ระบบออฟไลน์',
        'control_room_fullscreen' => 'เต็มหน้าจอ',
        'control_room_initializing' => 'กำลังเริ่มต้นอุปกรณ์...',
        'control_room_no_devices' => 'ไม่พบอุปกรณ์',
        'control_room_online_devices' => 'อุปกรณ์ออนไลน์',
        'control_room_recent_activity' => 'กิจกรรมล่าสุด',
        'control_room_loading_logs' => 'กำลังโหลดบันทึก...',
        'control_room_no_recent_activity' => 'ไม่มีกิจกรรมล่าสุด',
        'control_room_seen' => 'พบ',
        'control_room_ago' => 'ที่ผ่านมา',
        'control_room_total_events' => 'เหตุการณ์ทั้งหมด',
        'control_room_unit_s' => 'วิ',
        'control_room_unit_m' => 'นาที',
        'control_room_unit_h' => 'ชม.',
        'dashboard_loading' => 'กำลังโหลด...',
        'dashboard_please_wait' => 'โปรดรอสักครู่...',
        'dashboard_no_devices_detected' => 'ไม่พบอุปกรณ์',
        'dashboard_waiting_signals' => 'รอสัญญาณ...',
        'dashboard_unknown_location' => 'ไม่ทราบสถานที่',
        'dashboard_unknown_id' => 'ไม่ทราบรหัส',
        'dashboard_last_seen' => 'พบล่าสุด',

        'index_clock_loading' => 'กำลังโหลด...',
        'index_system_status' => 'สถานะระบบ',
        'index_connection' => 'การเชื่อมต่อ',
        'index_checking' => 'กำลังตรวจสอบ...',
        'index_waiting_signal' => 'รอสัญญาณ...',
        'index_active_devices' => 'อุปกรณ์ที่ใช้งาน',
        'index_loading_devices' => 'กำลังโหลดอุปกรณ์...',
        'index_login_method_admin' => 'ผู้ดูแล',
        'page_latency_title' => 'มอนิเตอร์ความหน่วง',
        'page_latency_subtitle' => 'ESP32 → เซิร์ฟเวอร์ → LINE',
        'page_status_title' => 'สถานะอุปกรณ์',
        'page_status_subtitle' => 'ติดตาม Heartbeat',
        'page_history_title' => 'ประวัติ',
        'page_history_subtitle' => 'บันทึกเหตุการณ์ฉุกเฉิน',
        'page_diagnostics_title' => 'ตรวจสอบระบบ',
        'page_diagnostics_subtitle' => 'สุขภาพระบบ / การเชื่อมต่อ',
        'page_live_title' => 'เรียลไทม์',
        'page_live_subtitle' => 'สตรีมเหตุการณ์ (SSE)',

        'history_device' => 'อุปกรณ์',
        'history_location' => 'สถานที่',
        'history_export_csv' => 'ส่งออก CSV',
        'history_hint' => 'API ส่งกลับล่าสุด 50 รายการ แล้วค่อยกรองในหน้า',
        'history_table_time' => 'เวลา',
        'history_table_device' => 'อุปกรณ์',
        'history_table_location' => 'สถานที่',
        'history_table_event' => 'เหตุการณ์',
        'history_table_status' => 'สถานะ',

        'status_hint' => 'สถานะ online: ภายใน 65 วินาทีล่าสุด',
        'status_connected' => 'เชื่อมต่อ',
        'status_disconnected' => 'ไม่เชื่อมต่อ',
        'status_online' => 'ออนไลน์',
        'status_offline' => 'ออฟไลน์',
        'status_last_seen' => 'พบล่าสุด',
        'status_seconds_ago' => 'กี่วินาทีที่ผ่านมา',
        'status_no_heartbeat' => 'ยังไม่มีบันทึก heartbeat',

        'latency_recent_events' => 'เหตุการณ์ล่าสุด',
        'latency_hint' => 'ดู p50/p95/p99 ที่ฝั่ง Server และเวลา LINE API ตอบกลับ',
        'latency_showing_last' => 'แสดงล่าสุด',
        'latency_events' => 'รายการ',
        'latency_emergency' => 'ฉุกเฉิน',
        'latency_heartbeat' => 'ฮาร์ทบีท',
        'latency_auth_fail' => 'ยืนยันตัวตนล้มเหลว',
        'latency_rate_limit' => 'จำกัดอัตรา',
        'latency_invalid_action' => 'แอคชันไม่ถูกต้อง',
        'latency_table_time' => 'เวลา',
        'latency_table_action' => 'แอคชัน',
        'latency_table_device' => 'อุปกรณ์',
        'latency_table_location' => 'สถานที่',
        'latency_table_seq' => 'ลำดับ',
        'latency_table_server_ms' => 'เวลาเซิร์ฟเวอร์ (ms)',
        'latency_table_line_ms' => 'เวลา LINE API (ms)',
        'latency_table_line_http' => 'LINE HTTP',
        'latency_table_request_id' => 'รหัสคำขอ',

        'diagnostics_hint' => 'หน้านี้ช่วยเช็ค DNS/TLS ไป LINE, สิทธิ์เขียน logs, และสถานะ config โดยไม่โชว์ secrets',
        'diagnostics_hints_title' => 'คำแนะนำ',
        'diagnostics_line_dns' => 'LINE DNS',
        'diagnostics_line_tls' => 'LINE TLS',
        'diagnostics_config' => 'คอนฟิก',
        'diagnostics_filesystem' => 'ไฟล์ระบบ',
        'diagnostics_php_openssl' => 'PHP/OPENSSL',
        'diagnostics_ok' => 'ปกติ',
        'diagnostics_warn' => 'เตือน',
        'diagnostics_fail' => 'ล้มเหลว',
        'diagnostics_ready' => 'พร้อมใช้งาน',
        'diagnostics_missing' => 'ขาดค่า',
        'diagnostics_writable' => 'เขียนได้',
        'diagnostics_not_writable' => 'เขียนไม่ได้',
        'diagnostics_hint_dns' => 'DNS ไป api.line.me ไม่ได้ (ตรวจเน็ต/DNS ของเครื่อง Server)',
        'diagnostics_hint_tls' => 'ต่อ TLS ไป LINE ไม่ได้ (มักเป็น cert/CA ใน PHP หรือ proxy/AV)',
        'diagnostics_hint_token' => 'ยังไม่ตั้งค่า LINE_CHANNEL_ACCESS_TOKEN ใน .env',
        'diagnostics_hint_user' => 'ยังไม่ตั้งค่า LINE_USER_ID ใน .env',
        'diagnostics_hint_esp_key' => 'ยังไม่ตั้งค่า ESP32_API_KEY ใน .env',
        'diagnostics_hint_logs' => 'โฟลเดอร์ logs เขียนไม่ได้ (permissions)',
        'diagnostics_hint_all_good' => 'ทุกอย่างดูพร้อมแล้ว',

        'live_connecting' => 'กำลังเชื่อมต่อ',
        'live_connected' => 'เชื่อมต่อแล้ว',
        'live_reconnect' => 'เชื่อมต่อใหม่',
        'live_event_feed' => 'ฟีดเหตุการณ์',
        'live_latest_heartbeat' => 'Heartbeat ล่าสุด',
        'live_latest_emergency' => 'ฉุกเฉินล่าสุด',
        'live_stream' => 'สตรีม',
        'live_msgs' => 'ข้อความ',
        'live_hint_buffer' => 'ถ้าเครือข่าย/Proxy buffer หนัก อาจเห็นหน่วงได้ ให้ดู Diagnostics และ Status ควบคู่',
        'live_is_connected' => 'เชื่อมต่อหรือไม่',
        'live_last_heartbeat' => 'Heartbeat ล่าสุด',
        'live_last_event' => 'เหตุการณ์ล่าสุด',
        'live_seconds_ago' => 'กี่วินาทีที่ผ่านมา',
        'live_type_heartbeat' => 'heartbeat',
        'live_type_emergency' => 'emergency',
        'live_type_ping' => 'ping',
        'live_type_error' => 'error',
    ],
    
    'en' => [
        // Login Page
        'login_title' => 'Login',
        'login_subtitle' => 'ResQTech Notification System',
        'username' => 'Username',
        'password' => 'Password',
        'username_placeholder' => 'Enter username',
        'password_placeholder' => 'Enter password',
        'login_button' => 'Login',
        'security_title' => 'Security System',
        'security_session' => 'Session Timeout',
        'security_brute' => 'Brute Force Protection',
        'security_csrf' => 'CSRF Protection',
        'security_headers' => 'Secure Headers',
        'logout_success' => 'Successfully logged out',
        'session_timeout' => 'Session expired. Please login again',
        'login_failed' => 'Invalid username or password',
        'too_many_attempts' => 'Too many login attempts. Please wait {minutes} minutes',
        'or_login_with' => 'Or sign in with',
        'sign_in_google' => 'Sign in with Google',
        
        // Index Page
        'system_title' => 'ResQTech System',
        'system_subtitle' => 'Smart Notification & Management Platform',
        'hello_user' => 'Hello, {username}!',
        'login_time' => 'Logged in at: {time}',
        'logout' => 'Logout',
        'send_notification' => 'Send Notification',
        'notification_title' => 'Send Notification',
        'notification_desc' => 'Click the button below to send notification to LINE Official Account immediately',
        'notification_message_label' => 'Message / Details',
        'notification_message_placeholder' => 'Type the details to send to LINE...',
        'send_button' => 'Send Notification',
        'sending' => 'Sending...',
        'send_success' => 'Notification sent successfully!',
        'send_error' => 'An error occurred! Please check the log',
        'connection_error' => 'Unable to connect to server',
        'loading_clock' => 'Loading...',
        
        // General
        'theme_toggle' => 'Toggle Theme',
        'language' => 'Language',
        'thai' => 'ไทย',
        'english' => 'English',
        'profile' => 'Profile',

        'nav_home' => 'Home',
        'nav_dashboard' => 'Dashboard',
        'nav_control' => 'Control Room',
        'nav_latency' => 'Latency',
        'nav_status' => 'Status',
        'nav_history' => 'History',
        'nav_diagnostics' => 'Diagnostics',
        'nav_live' => 'Live',
        'nav_logout' => 'Logout',
        'nav_more' => 'More',

        'common_refresh' => 'Refresh',
        'common_raw_json' => 'Raw JSON',
        'common_last' => 'Last',
        'common_count' => 'Count',
        'common_live' => 'Live',
        'common_error' => 'Error',
        'common_loading' => 'Loading...',
        'common_no_data' => 'No data',
        'common_fetch_failed' => 'Fetch failed',
        'common_auto_refresh' => 'Auto Refresh',
        'common_off' => 'off',
        'common_on' => 'on',
        'common_limit' => 'Limit',
        'common_action' => 'Action',
        'common_all' => 'all',

        'page_dashboard_title' => 'Dashboard',
        'page_dashboard_subtitle' => 'Real-time Monitoring',
        'dashboard_marquee_title' => 'ResQTech Dashboard',
        'dashboard_marquee_subtitle1' => 'Emergency Monitoring System',
        'dashboard_marquee_subtitle2' => 'Real-time Updates',
        'dashboard_marquee_subtitle3' => '24/7 Protection',
        'dashboard_total_events' => 'Total Events',
        'dashboard_all_time' => 'All time',
        'dashboard_today_events' => 'Today\'s Events',
        'dashboard_last_24h' => 'Last 24 Hours',
        'dashboard_recent' => 'Recent',
        'dashboard_esp32_status' => 'ESP32 Status',
        'dashboard_uptime' => 'Uptime',
        'dashboard_last_heartbeat' => 'Last Heartbeat',
        'dashboard_active_devices' => 'Active Devices',
        'dashboard_active_devices_subtitle' => 'Real-time status of all connected ESP32 units',
        'dashboard_events_overview' => 'Events Overview',
        'dashboard_events_overview_subtitle' => 'Emergency events statistics',
        'dashboard_timeline_title' => 'Activity Timeline',
        'dashboard_timeline_subtitle' => 'Last 7 days activity',
        'dashboard_recent_events' => 'Recent Events',
        'dashboard_recent_events_subtitle' => 'Latest emergency notifications',
        'dashboard_no_events_yet' => 'No events recorded yet',
        'dashboard_chart_today' => 'Today',
        'dashboard_chart_last24h' => 'Last 24h',
        'dashboard_chart_last7d' => 'Last 7 Days',
        'dashboard_chart_older' => 'Older',
        'dashboard_chart_events' => 'Events',

        'control_room_title' => 'Control Room',
        'control_room_subtitle' => 'ResQTech War Room',
        'control_room_war_room' => 'WAR ROOM',
        'control_room_emergency_alert' => 'EMERGENCY ALERT',
        'control_room_unknown_location' => 'UNKNOWN LOCATION',
        'control_room_unknown_device' => 'UNKNOWN',
        'control_room_acknowledge' => 'ACKNOWLEDGE',
        'control_room_system_online' => 'SYSTEM ONLINE',
        'control_room_system_offline' => 'SYSTEM OFFLINE',
        'control_room_fullscreen' => 'Fullscreen',
        'control_room_initializing' => 'Initializing Device Wall...',
        'control_room_no_devices' => 'No devices found',
        'control_room_online_devices' => 'Online Devices',
        'control_room_recent_activity' => 'Recent Activity',
        'control_room_loading_logs' => 'Loading logs...',
        'control_room_no_recent_activity' => 'No recent activity',
        'control_room_seen' => 'Seen',
        'control_room_ago' => 'ago',
        'control_room_total_events' => 'Total Events',
        'control_room_unit_s' => 's',
        'control_room_unit_m' => 'm',
        'control_room_unit_h' => 'h',
        'dashboard_loading' => 'Loading...',
        'dashboard_please_wait' => 'Please wait...',
        'dashboard_no_devices_detected' => 'No devices detected',
        'dashboard_waiting_signals' => 'Waiting for signals...',
        'dashboard_unknown_location' => 'Unknown Location',
        'dashboard_unknown_id' => 'Unknown ID',
        'dashboard_last_seen' => 'Last seen',

        'index_clock_loading' => 'Loading...',
        'index_system_status' => 'System Status',
        'index_connection' => 'Connection',
        'index_checking' => 'CHECKING...',
        'index_waiting_signal' => 'Waiting for signal...',
        'index_active_devices' => 'Active Devices',
        'index_loading_devices' => 'Loading devices...',
        'index_login_method_admin' => 'Admin',
        'page_latency_title' => 'Latency Monitor',
        'page_latency_subtitle' => 'ESP32 → Server → LINE',
        'page_status_title' => 'Device Status',
        'page_status_subtitle' => 'Heartbeat Monitor',
        'page_history_title' => 'History',
        'page_history_subtitle' => 'Emergency Event Logs',
        'page_diagnostics_title' => 'Diagnostics',
        'page_diagnostics_subtitle' => 'System Health Check',
        'page_live_title' => 'Live',
        'page_live_subtitle' => 'Real-time SSE Stream',

        'history_device' => 'Device',
        'history_location' => 'Location',
        'history_export_csv' => 'Export CSV',
        'history_hint' => 'API returns latest 50 rows; filter in UI',
        'history_table_time' => 'time',
        'history_table_device' => 'device',
        'history_table_location' => 'location',
        'history_table_event' => 'event',
        'history_table_status' => 'status',

        'status_hint' => 'online: within last 65 seconds',
        'status_connected' => 'CONNECTED',
        'status_disconnected' => 'DISCONNECTED',
        'status_online' => 'ONLINE',
        'status_offline' => 'OFFLINE',
        'status_last_seen' => 'last_seen',
        'status_seconds_ago' => 'seconds_ago',
        'status_no_heartbeat' => 'No heartbeat log yet',

        'latency_recent_events' => 'Recent Events',
        'latency_hint' => 'Shows p50/p95/p99 on server and LINE API response time',
        'latency_showing_last' => 'Showing last',
        'latency_events' => 'events',
        'latency_emergency' => 'EMERGENCY',
        'latency_heartbeat' => 'HEARTBEAT',
        'latency_auth_fail' => 'AUTH_FAIL',
        'latency_rate_limit' => 'RATE_LIMIT',
        'latency_invalid_action' => 'INVALID_ACTION',
        'latency_table_time' => 'time',
        'latency_table_action' => 'action',
        'latency_table_device' => 'device',
        'latency_table_location' => 'location',
        'latency_table_seq' => 'seq',
        'latency_table_server_ms' => 'server_ms',
        'latency_table_line_ms' => 'line_ms',
        'latency_table_line_http' => 'line_http',
        'latency_table_request_id' => 'request_id',

        'diagnostics_hint' => 'Checks LINE DNS/TLS, log write access, and config status without exposing secrets',
        'diagnostics_hints_title' => 'Hints',
        'diagnostics_line_dns' => 'LINE DNS',
        'diagnostics_line_tls' => 'LINE TLS',
        'diagnostics_config' => 'CONFIG',
        'diagnostics_filesystem' => 'FILESYSTEM',
        'diagnostics_php_openssl' => 'PHP/OPENSSL',
        'diagnostics_ok' => 'OK',
        'diagnostics_warn' => 'WARN',
        'diagnostics_fail' => 'FAIL',
        'diagnostics_ready' => 'READY',
        'diagnostics_missing' => 'MISSING',
        'diagnostics_writable' => 'WRITABLE',
        'diagnostics_not_writable' => 'NOT WRITABLE',
        'diagnostics_hint_dns' => 'DNS to api.line.me failed (check server network/DNS)',
        'diagnostics_hint_tls' => 'TLS to LINE failed (often cert/CA in PHP or proxy/AV)',
        'diagnostics_hint_token' => 'LINE_CHANNEL_ACCESS_TOKEN not set in .env',
        'diagnostics_hint_user' => 'LINE_USER_ID not set in .env',
        'diagnostics_hint_esp_key' => 'ESP32_API_KEY not set in .env',
        'diagnostics_hint_logs' => 'logs folder not writable (permissions)',
        'diagnostics_hint_all_good' => 'Everything looks ready',

        'live_connecting' => 'CONNECTING',
        'live_connected' => 'CONNECTED',
        'live_reconnect' => 'Reconnect',
        'live_event_feed' => 'Event Feed',
        'live_latest_heartbeat' => 'Latest Heartbeat',
        'live_latest_emergency' => 'Latest Emergency',
        'live_stream' => 'Stream',
        'live_msgs' => 'Msgs',
        'live_hint_buffer' => 'Heavy proxy buffering may add delay; check Diagnostics and Status',
        'live_is_connected' => 'is_connected',
        'live_last_heartbeat' => 'last_heartbeat',
        'live_last_event' => 'last_event',
        'live_seconds_ago' => 'seconds_ago',
        'live_type_heartbeat' => 'heartbeat',
        'live_type_emergency' => 'emergency',
        'live_type_ping' => 'ping',
        'live_type_error' => 'error',
    ]
];

/**
 * Translate text
 */
function t(string $key, array $replacements = []): string {
    global $translations, $current_lang;
    
    $text = $translations[$current_lang][$key] ?? $key;
    
    foreach ($replacements as $placeholder => $value) {
        $text = str_replace('{' . $placeholder . '}', $value, $text);
    }
    
    return $text;
}

/**
 * Get language switch URL
 */
function getLangUrl(string $lang): string {
    $currentUrl = $_SERVER['REQUEST_URI'];
    $parsedUrl = parse_url($currentUrl);
    
    $params = [];
    if (isset($parsedUrl['query'])) {
        parse_str($parsedUrl['query'], $params);
    }
    
    $params['lang'] = $lang;
    
    return $parsedUrl['path'] . '?' . http_build_query($params);
}

/**
 * Get current language
 */
function getCurrentLang(): string {
    global $current_lang;
    return $current_lang;
}
